# Generated by Django 2.1.7 on 2019-03-27 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_brands', models.CharField(max_length=100)),
                ('product_url', models.URLField(max_length=300)),
                ('product_creator', models.CharField(max_length=100)),
                ('product_nutriscore', models.CharField(max_length=10)),
                ('product_image_url', models.URLField(max_length=300)),
                ('product_kcal', models.IntegerField()),
                ('product_kj', models.IntegerField()),
                ('product_sugar', models.IntegerField()),
                ('product_satured_fat', models.IntegerField()),
                ('product_fat', models.IntegerField()),
                ('product_salt', models.IntegerField()),
                ('product_nova', models.IntegerField()),
            ],
            options={
                'verbose_name': 'products',
                'ordering': ['product_name'],
            },
        ),
    ]
