# Generated by Django 2.1.7 on 2019-03-27 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_auto_20190327_1214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_satured_fat',
            new_name='product_saturated_fat',
        ),
    ]
