# Generated by Django 2.1.7 on 2019-03-27 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_auto_20190327_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_fat',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_nova',
            field=models.IntegerField(null=True),
        ),
    ]
