# Generated by Django 2.1.7 on 2019-03-27 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0007_auto_20190327_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_fat',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='product_nova',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='product_salt',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='product_saturated_fat',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='product_sugar',
            field=models.FloatField(),
        ),
    ]
