# Generated by Django 2.1.7 on 2019-03-27 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0008_auto_20190327_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_categories',
            field=models.CharField(default='test', max_length=300),
            preserve_default=False,
        ),
    ]
