# Generated by Django 2.1.7 on 2019-03-27 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0009_product_product_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_categories',
            field=models.CharField(max_length=500),
        ),
    ]
